# Generated by Django 4.2.3 on 2023-07-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_profiel_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previous_job',
            new_name='previous_role',
        ),
    ]
